### ISSUE TITLE
B.1.1 Verify the requester's qualification is authorized

### ISSUE THREAD

**Issue by chuiheng-wu** [perspicacious-slinki/Immutable2023s1ANUTechlauncher#14]

**Comment by chuiheng-wu** [comment]
**Acceptance Criteria:** The system is able to update the verification status including awaiting verified, verifying, and verified.

**Comment by JeremiahXing** [comment]
Accept criteria:
1. The system shall provide a form for the requester to enter their personal information.
2. The system shall send the request to the authorized institutions and send notifications to the institutions.
3. Once the request is been confirmed and validated, the admin can update the request's statues so that the user can mint it as NFT.

**Comment by JeremiahXing** [comment]
Final Review: 
**UI/UX check**: pass
**Code quality check**: pass
